### PR TITLE
Add second example SN74LS00N

### PR DESCRIPTION
**Pull request by ouabache**
…ltiple symbols

### CODE REVIEW

**Comment by ubruhin** [comment]
Hi,

Is there a reason why adding a new example instead of extending the already existing example? IMHO it would be cleaner/simpler to add a second symbol variant to LMV321LILT instead (it's an OpAmp, we could add a separate symbol variant for split power/amplifier symbols).

Beside this, my thoughts about your changes:
- All library elements which were used in screenshots should be added to the workspace in the directory `resources/workspace`, otherwise someone else isn't able to reproduce the screenshots ( I just realized that this workspace had a pre-0.1 file format, I just fixed this on the `master` branch).
- The new screenshots look different compared to other screenshots. We should provide consistent look&feel across all screenshots, which means:
  - Use small window size to get screenshots filled with "information" instead of blank areas (a 1920x1080 screenshot where the relevant information is in an area of 100x100px is wasted space).
  - If reasonable, highlight the relevant information in screenshots with red boxes/circles/arrows
  - Use "me" as library element Author
- The text is also written differently to the current text style. You used the "we" perspective ("Now we add...", "We have to..."), while the current text uses the "you" perspective ("Now you should...", "You have to ...").
- You committed a backup file -> remove it
- There are a lot of empty lines added -> use 2 empty lines to separate chapters, only 1 empty line within chapters.

I'm sorry, it seems that those contribution guidelines are not documented yet - I'll fix this since it is not very friendly to contributors...

**Comment by ouabache** [comment]
Hi Urban,

Thanks for the feedback. I missed the resources directory and will go back
and fix everything.

The reason I did not use the LMV32 op amp as an example is that I wanted to
show a case with multiple gates. There are versions
with 2 or 4 op amps but they are in different packages. The 7400 can do
that in one package.

John Eaton

**Comment by ubruhin** [comment]
> The reason I did not use the LMV32 op amp as an example is that I wanted to
show a case with multiple gates.

Sure, but a single OpAmp could also be represented by two symbols, a power symbol and a amplifier symbol ;)

However, I thought a bit about this and now I wonder if we should document symbol variants in the "Getting Started With LibrePCB" section at all. Since it's only a getting started guide, I think we should keep it as simple as possible. I would suggest to add a new top level section, called "User Manual" or something like that, which could then contain more detailed documentation about LibrePCB's features. Symbol Variants could then documented here too.

In addition, I would even simplify the current chapter structure by removing the "Adding Libraries" and "Example: LMV321LILT" chapters:
grafik ---> grafik

Any opinions @ouabache @dbrgn?

**Comment by dbrgn** [comment]
Sounds good to me.

What would be fantastic for getting started is a video tutorial where you (or someone else) creates a symbol + component + package + device for an example part.

**Comment by ouabache** [comment]
I agree that the "Getting Started" section should be designed to get a
first time user up and running and seeing results as quickly
as possible. The "out-of-box experience" can make the difference between
someone who dumps the product after their first use
verses someone who goes on to use it all the time. You want to start off
with training wheels.

We do need a reference section where we cover all the commands. I like how
getting started uses screen shots with the circles and
arrows to guide the user. It took me a few attempts before I realized that
selecting a symbol didn't do anything unless you pressed the
green + key.

I am bothered that the symbol variants don't work quite the way that I had
hoped they would. If I do a board with 7 op amps then I need
to package them either 1,2 or 4 per package. I want to place 7 symbols on
the schematic and do the packaging later when I am placing
components on the board blank. Even though all three packages use the same
symbol I cannot add a single op amp and then later put
it in a quad package without deleting and readding it.


John Eaton

**Comment by ubruhin** [comment]
> Sounds good to me.

Ok, done in #39. @ouabache could you rebase this branch and move the symbol variant documentation into a separate chapter, as discussed above?

> I am bothered that the symbol variants don't work quite the way that I had
hoped they would. If I do a board with 7 op amps then I need
to package them either 1,2 or 4 per package. I want to place 7 symbols on
the schematic and do the packaging later when I am placing
components on the board blank. Even though all three packages use the same
symbol I cannot add a single op amp and then later put
it in a quad package without deleting and readding it.

(Although not related to this PR:) The problem is the power symbol (VCC/GND) - if you need 7 OpAmps, you have to place 7 power symbols when using single OpAmps. With 2 per package you need 4x power, with 4 per package you only need 2x power. So in schematics you have to know how many OpAmps are in the package anyway, no matter how symbol variants work exactly.

**Comment by ouabache** [comment]
The circuit designer doesn't worry about packaging. They do their design
with no power connections.

Bread board engineer takes that schematic and decides to breadboard it
using 7 op amps so they add 7 power blocks on a second
sheet. Production board engineer goes with 2 quad packages for the
production board and adds 2 power blocks to their second sheet.
Both are using the same design so if it changes then everyone stays in sync.

In today's world you place a part and you do not know if the board is going
to be thru hole or surface mount. That will be decided later
by another engineer and your design may be used on multiple boards. That's
the beauty of LibrePCB is that I can place a component and
let the layout engineer pick the package. We should extend this to also
cover repacking gates into different packages.

I will move the symbol variant stuff into a separate chapter.

**Comment by ouabache** [comment]
Ok, I added a paragraph and graphic showing a component symbol variant. I
had to update LibrePCB_Base in resources so a
bunch of files changed.
Pull request has been made.

**Comment by rnestler** [comment]
@ubruhin What is the status on this?

**Comment by ubruhin** [comment]
There are still several issues not fixed (see https://github.com/LibrePCB/librepcb-doc/pull/36#issuecomment-535938392 and https://github.com/LibrePCB/librepcb-doc/pull/36#issuecomment-539650880). In addition, the whole repository structure has changed in the mean time since we switched to Antora.

If there's still any motivation in documenting multi-symbol components, I'd suggest to open a new PR with all the feedback from this thread implemented. Thus I'll close this for now - sorry!

**Pull request closed without merging**
